name: CI CD

on:
  workflow_dispatch:
    inputs:
      ENVIRONMENT:
        description: 'Set environment'
        type: environment
        required: true
      ec2ip:
        required: true
        default: 35.179.74.229
        description: 'host'

env:
  FOLDER_PATH: /home/c8prod/captiv8.io

jobs:
  get_vars:
    name: Expose variables
    uses: ./.github/workflows/vars.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}

  build-and-deploy:
    name: Test inputs
    needs: get_vars
    uses: ./.github/workflows/deploy.yml
    with:
      ENVIRONMENT: ${{ inputs.ENVIRONMENT }}
      SSH_HOST: ${{ needs.get_vars.outputs.DEPLOY_TO }}
      FOLDER_PATH: ${{ needs.get_vars.outputs.FOLDER_PATH }}
    secrets: inherit
