name: Build

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Set environment (alpha, dev, staging)'
        required: true
        default: 'alpha'
      ec2ip:
        required: true
        default: 3.10.173.82

env:
  FOLDER_PATH: /home/c8prod/captiv8.io
  ALPHA: c8prod@platform.alpha.captiv8.io
  DEVELOP: c8prod@platform.dev.captiv8.io
  STAGING: c8prod@platform.staging.captiv8.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Setup SSH key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.EC2_SSH_KEY }}" > "$HOME/.ssh/key.pem"
      - run: chmod 400 "$HOME/.ssh/key.pem"
      - run: ssh -i "$HOME/.ssh/key.pem" ubuntu@${{ github.event.inputs.ec2ip }}
