name: Build

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Set environment (alpha, dev, staging)'
        required: true
        default: 'alpha'
      ec2ip:
        required: true
        default: 35.179.74.229
        description: 'host'
        
env:
  FOLDER_PATH: /home/c8prod/captiv8.io

jobs:
  build:
    name: Test inputs
    runs-on: ubuntu-latest
    steps:
      - name: Test via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ github.event.inputs.ec2ip }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            mkdir ${{ env.FOLDER_PATH }}/${{ github.event.inputs.env }}
            cd ${{ env.FOLDER_PATH }}
            pdw
            ls -la
            date
