name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        description: 'Environment name'
        type: string
        required: true
      FOLDER_PATH:
        description: 'Folder path'
        type: string
        required: true
      SSH_HOST:
        description: 'Host name'
        type: string
        required: true
      EC2IP:
        description: 'ec2 ip address'
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Test via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ inputs.EC2IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd ${{ inputs.FOLDER_PATH }}/github-actions
            pwd
            echo "${{ inputs.SSH_HOST }}"
            echo "${{ secrets.EC2_SSH_KEY }}" >> "${{ inputs.ENVIRONMENT }}"    
            whoami