name: Build

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Set environment (alpha, dev, staging)'
        required: true
        default: 'alpha'
      ec2ip:
        required: true
        default: 3.10.173.82

env:
  FOLDER_PATH: /home/c8prod/captiv8.io
  ALPHA: c8prod@platform.alpha.captiv8.io
  DEVELOP: c8prod@platform.dev.captiv8.io
  STAGING: c8prod@platform.staging.captiv8.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: 3.10.173.82
          SSH_PORT: 22
          SSH_USER: ubuntu
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} pwd
      - run: ssh ${{ steps.ssh.outputs.SERVER }} echo "123test" > hello.txt
